FROM node:22-slim

RUN apt-get update && apt-get install -y git build-essential python3 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN npm install --workspace node

EXPOSE 5000

CMD ["npm","run","dev:node"]