FROM node:22-slim

RUN apt-get update && apt-get install -y git build-essential python3 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN npm install --workspace relayer

EXPOSE 5005

CMD ["npm","run","dev:relayer"]