FROM node:22-slim

RUN apt-get update && apt-get install -y git build-essential python3

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm run install

COPY . .

EXPOSE 5005
CMD ["npm", "run", "dev:relayer"]